# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GenIV Solutions Inc.
description: >- # this means to ignore newlines until "domainUrl:"
  GenIV Solutions Inc. is the next step in the journey to bring a positive impact not only to the local community in Kelowna, BC, but also across Canada and the United States. We look forward to serving you with their IT needs.
domainUrl: "https://geniv.ca"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geniv.ca" # the base hostname & protocol for your site, e.g. http://example.com

author: George Davis
email: gdcrocx@yahoo.in
twitter_username: GDCrocx
github_username: geniv-solutions-inc
contact_number: (647)561-7328

permalink: pretty

# Hosting settings
port: 80

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude: ['README.md']

# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google Analytics
google_tag_id: G-88XNDKPL6M